name: "Run CI"

on: [push]

jobs:
  build-sdks:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: ["VitalDevices"]
    steps:
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination 'generic/platform=iOS'
        env:
          scheme: ${{ matrix.scheme }}

  test-sdks:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: ["VitalHealthKit", "VitalCore"]
    steps:
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          xcodebuild clean test -scheme "${scheme}" -destination platform=iOS\ Simulator,OS=15.5,name=iPhone\ 13
        env:
          scheme: ${{ matrix.scheme }}
