name: "Run CI"

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=12.2,name=iPhone X"]
        scheme: ["VitalHealthKit", "VitalDevices"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
          scheme: ${{ matrix.scheme }}
