name: "Run CI"

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        scheme: ["VitalHealthKit", "VitalDevices"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination 'generic/platform=iOS'
        env:
          scheme: ${{ matrix.scheme }}
