name: "Run CI"

on: [push]

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        scheme: ["VitalHealthKit"]
    steps:
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_13.4.app
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination 'generic/platform=iOS'
        env:
          scheme: ${{ matrix.scheme }}
